Post:
  type: object
  config:
    description: "A post"
    fields:
      id:
        type: "Int!"
      title:
        type: "String"
      content:
        type: "String"
      author:
        type: "Author"

